### ISSUE TITLE
Season 29 Missing

### ISSUE THREAD

**Issue by eracknaphobia** [eracknaphobia/plugin.video.simpsonsworld#8]
Is it just me? Season 29 is empty when navigating to it. This also throws an error in random episode when it tries to play a season 29  episode.

`Traceback (most recent call last):
                                              File "C:\Users\nuc\AppData\Roaming\Kodi\addons\plugin.video.simpsonsworld\simpsons.py", line 26, in <module>
                                                random_episode()
                                              File "C:\Users\nuc\AppData\Roaming\Kodi\addons\plugin.video.simpsonsworld\resources\lib\globals.py", line 107, in random_episode
                                                enum = random.randint(1, elen)
                                              File "C:\Program Files\Kodi\system\python\Lib\random.py", line 242, in randint
                                                return self.randrange(a, b+1)
                                              File "C:\Program Files\Kodi\system\python\Lib\random.py", line 218, in randrange
                                                raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
                                            ValueError: empty range for randrange() (1,0, -1)`

**Comment by hackthis02** [comment]
I think there might be something on their side. I ran the 29th season URL thru postmen and got 
``` 
{
    "videos": []
} 
```
but when I ran 28 or 30 I got the correct json. But it makes since I've been randomly getting an error when running a random episode. I just thought it was an out of range exception.

**Comment by eracknaphobia** [comment]
Thanks for verifying that.

**Comment by hackthis02** [comment]
Where you ever able to see what your Android TV sends out for season 29?

**Comment by eracknaphobia** [comment]
Yeah, but it wasn't helpful. Would require refactoring a bunch of other code in order to make it work.

**Comment by hackthis02** [comment]
That might be to kill off "unofficial" apps. Shot me the url and I'll see if I can work it in.
